name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.bhanutejaravutla }}
          password: ${{ secrets.dckr_pat_kb3h-RfSlTc1OwDm2f-6jDxUaGk }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.bhanutejaravutla }}/go-app:latest
